"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []

# DEBUG = False
# ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mptt',

    'mq',
    'order',
    'user',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'common.middlewares.PutOrDeleteMiddleware',
    'common.middlewares.HTTPHeadersSetMiddleware',
    # 'common.middlewares.APIVersionControlMiddleware',
    'common.middlewares.WebHeadersMiddleware',
    # 'common.middlewares.VerifySignatureMiddleware',
    'common.middlewares.ExceptionHandlerMiddleware',
)

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(__file__), 'templates').replace('\\','/'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

# Session
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_AGE = 1209600 # 14 days
# SESSION_COOKIE_DOMAIN = '.youyulx.com'
# SESSION_COOKIE_HTTPONLY = False

# If this is set to True, the cookie will be marked as "secure", 
# which means browsers may ensure that the cookie is 
# only sent under an HTTPS connection.
# SESSION_COOKIE_SECURE = True 


# Cache
CACHE_SCOPE_DELIMITER = ':'
CACHE_KEY_PREFIX = 'youyulx_partner'
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': ['redis://127.0.0.1:6379/6'],
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'MAX_ENTRIES' : 500000,
            # "SOCKET_CONNECT_TIMEOUT": 5,  # in seconds
            # "SOCKET_TIMEOUT": 5,  # in seconds
            "IGNORE_EXCEPTIONS": True,
        },
        'KEY_FUNCTION': lambda key, prefix, version: CACHE_SCOPE_DELIMITER.join((prefix, key)),
        'KEY_PREFIX': CACHE_KEY_PREFIX,
        'TIMEOUT': 180,
        # New in Django 1.7.
        # You can set TIMEOUT to None so that, by default, cache keys never expire.
        # 'TIMEOUT': None,
    },
}


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE'    : 'django.db.backends.postgresql_psycopg2',
        'NAME'      : 'db_youyulx_partner',
        'USER'      : '',
        'PASSWORD'  : '',
        'HOST'      : '',
        'PORT'      : '',
        # 'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 300,  # 5 mins
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False

USE_I18N = True
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#------------------------------------------------
# Project #
#------------------------------------------------

APP_NAME    = 'YouYuLX_Partner'
API_VERSION = '1.0'

DATA_FORMAT = "json"

TS_AVAILABLE_SECONDS = 300

ACCOUNT_PREFIX = "..."

# DEBUG
# WEB_CLIENT_ID = ''
# WEB_SECRET_KEY = ''

# IOS_CLIENT_ID = ''
# IOS_SECRET_KEY = ''

# ANDROID_CLIENT_ID = ''
# ANDROID_SECRET_KEY = ''

# SERVER_CLIENT_ID = ''
# SERVER_SECRET_KEY = ''

# Release
# WEB_CLIENT_ID = ''
# WEB_SECRET_KEY = ''

# IOS_CLIENT_ID = ''
# IOS_SECRET_KEY = ''

# ANDROID_CLIENT_ID = ''
# ANDROID_SECRET_KEY = ''

# SERVER_CLIENT_ID = ''
# SERVER_SECRET_KEY = ''


NO_VERIFY_PATH = (
    '/ts', 
)

VERSION_PASS_PATH = (
    '/ts', 
)

WEB_HEADERS = {
    "Access-Control-Allow-Origin"  : "*",
    "Access-Control-Allow-Headers" : "Content-Type, AUTHORIZATION",
    "Access-Control-Allow-Methods" : "GET,POST,PUT,DELETE,OPTIONS",
    "Access-Control-Allow-Credentials" : "true",
}

MANAGE_BACKEND_BASE_URL = ''

DEFAULT_INDEX = '1'
DEFAULT_SIZE = '10'

from mq.settings import *

from msg.settings import *

from order.settings import *

from product.settings import *

from share.settings import *

from user.settings import *

